variables:
  STACK_NAME: robot-app-v2

stages:
  - test
  - build
  - publish_nuget
  - deploy

before_script:
  - unset DOCKER_HOST

default:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  cache:
    key: nuget-and-node-cache
    paths:
      - ~/.nuget/packages/
      - node_modules/

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - dotnet restore
    - cd robot-project-v3.client
    - npm install
  script:
    - dotnet build --no-restore
    - dotnet test --no-build --no-restore

create_docker_image:
  stage: build
  image: docker:latest
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  needs: [ "test" ]
  dependencies:
    - test
  only:
    - main
  artifacts:
    paths:
      - docker-compose.yml

publish_nuget_package:
  stage: publish_nuget
  script:
    - dotnet restore
    - find . -name "RobotAppLibrary*.csproj" -exec dotnet pack {} -c Release -o ./packages --property:Version=$CI_COMMIT_TAG \;
    - dotnet nuget push ./packages/*.nupkg -k $CI_JOB_TOKEN -s $CI_SERVER_PROTOCOL://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json
  only:
    - tags
  dependencies:
    - test
  artifacts:
    paths:
      - ./packages/*.nupkg
    expire_in: 1 day




deploy:
  stage: deploy
  image: docker:latest
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d --build
  needs: [ "create_docker_image" ]
  dependencies:
    - create_docker_image
  only:
    - main
  environment:
    name: production
    url: https://robot.botbot.fr
